spring:
  profiles: dev
  redis:
    host: 172.16.105.145
    port: 6379
  kafka:
    bootstrap-servers: 172.31.206.121:9092

server:
  port: 8199

eureka:
  client:
    service-url:
      defaultZone: http://discoveryservice.dev.saas.dyrs.online/eureka

logging:
  path: D:\logs
  pattern:
    level: INFO